[meta]
name = "Current Effects"
author = "Ezio"
category = "Overlay"
version = "0.23.1"
siteid = 382

[script]
dependencies = [ "VehicleState" ]
exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]
module = "CurrentEffects"
